# Generated by Django 3.2.8 on 2022-01-13 13:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('invest_app', '0006_auto_20220111_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='invested_date',
            field=models.DateTimeField(default=django.utils.timezone.localtime),
        ),
    ]
